# Render each article's "What to cite" section from the verb specs' `cite` entries.
#
#   Rscript scripts/render-cite.R           # rewrite the sections in vignettes/*.Rmd
#   Rscript scripts/render-cite.R --check   # CI: fail if any section differs from its specs
#
# A citation typed into an article is a fact that can drift from the spec it came from, as every
# count and version in this package's prose once did. So each article carries a generated block
# between two markers, listing every DOI the specs of the verbs it teaches cite, with what each is
# cited for. The DOIs themselves are the bridge's: fix one there, sync, and re-run this.
#
# Base R and the installed package's own JSON reader, like scripts/build-man.R.

args <- commandArgs(trailingOnly = TRUE)
check <- identical(args, "--check")
if (!dir.exists("R") || !file.exists("DESCRIPTION")) {
  stop("run this from the package root")
}
json_parse <- getFromNamespace("json_parse", "mzLibR")

# Which specs each article teaches, by module (and genes resolve, which the proteins article
# teaches though its module is `genes`).
ARTICLE_SPECS <- list(
  readers = "^readers[.]",
  sdrf = "^sdrf[.]",
  isobaric = "^isobaric[.]",
  pride = "^pride[.]",
  proteins = "^(proteins|genes)[.]",
  peptidoforms = "^peptidoform[.]",
  flashlfq = "^quant[.]",
  stats = "^stats[.]"
)

BEGIN <- "<!-- BEGIN cite: generated by scripts/render-cite.R from the verb specs; do not edit -->"
END <- "<!-- END cite -->"

read_spec <- function(path) {
  json_parse(paste(readLines(path, warn = FALSE, encoding = "UTF-8"), collapse = "\n"))
}

cite_block <- function(pattern) {
  specs <- sort(list.files(file.path("docs", "specs"), pattern = "[.]json$"))
  specs <- specs[grepl(pattern, specs)]
  seen <- character(0)
  lines <- character(0)
  for (file in specs) {
    spec <- read_spec(file.path("docs", "specs", file))
    for (entry in spec$cite) {
      doi <- entry$doi
      if (is.null(doi) || doi %in% seen) next
      seen <- c(seen, doi)
      # Parentheses in a DOI (10.1016/0197-2456(86)90046-2) are escaped in the link target, so no
      # markdown reader can end the link early.
      target <- gsub(")", "%29", gsub("(", "%28", doi, fixed = TRUE), fixed = TRUE)
      lines <- c(lines, paste0("- [doi:", doi, "](https://doi.org/", target, "): ", entry[["for"]], "."))
    }
  }
  if (length(lines) == 0L) {
    lines <- "- No publication: these verbs cite none in their specs."
  }
  c(BEGIN, "", lines, "", END)
}

problems <- character(0)
for (article in names(ARTICLE_SPECS)) {
  path <- file.path("vignettes", paste0(article, ".Rmd"))
  text <- readLines(path, warn = FALSE, encoding = "UTF-8")
  begin <- which(text == BEGIN)
  end <- which(text == END)
  if (length(begin) != 1L || length(end) != 1L || end < begin) {
    problems <- c(problems, paste0(path, ": needs exactly one '", BEGIN, "' ... '", END, "' block"))
    next
  }
  wanted <- c(text[seq_len(begin - 1L)], cite_block(ARTICLE_SPECS[[article]]), text[-seq_len(end)])
  if (!identical(wanted, text)) {
    if (check) {
      problems <- c(problems, paste0(path, ": the cite block differs from the specs"))
    } else {
      con <- file(path, open = "wb")
      writeBin(charToRaw(enc2utf8(paste0(paste(wanted, collapse = "\n"), "\n"))), con)
      close(con)
      cat("rewrote ", path, "\n", sep = "")
    }
  }
}
if (length(problems) > 0L) {
  cat(paste0("  ! ", problems, "\n"), sep = "")
  cat("Run: R CMD INSTALL . && Rscript scripts/render-cite.R\n")
  quit(status = 1L)
}
cat(length(ARTICLE_SPECS), "articles: every cite block matches its specs\n")
